<?xml version="1.0"?>

<!-- ros2 launch bam_descriptions display.launch.py model:='robots/aruco_calib_v1.urdf.xacro' -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bam_v1_left">
  <!-- Define New Base Link in Center -->
  <xacro:include filename="$(find bam_descriptions)/urdf/common.xacro" />

  <xacro:arg name="transport_path" default=""/>
  <xacro:property name="transport_path" value="$(arg transport_path)" />

  <xacro:arg name="mock_hardware" default="false"/>
  <xacro:property name="mock_hardware" value="$(arg mock_hardware)" />

  <link name="base_link"/>

  <joint name="rack_fixed_joint" type="fixed">
      <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0 0" />
      <parent link="base_link" />
      <child link="rack" />
  </joint>

  <link name="rack">
    <visual>
      <geometry>
        <mesh filename="package://bam_descriptions/meshes/aruco/aruco_calibration.stl"/>
      </geometry>
      <material name="Ghost"/>
    </visual>
  </link>

  <joint name="camera_fixed_joint" type="fixed">
      <origin xyz="0.0 0.205 -0.003" rpy="0 0 0" />
      <parent link="rack" />
      <child link="camera_base_link" />
  </joint>

  <link name="camera_base_link"/>

  <!-- Real Sense -->
  <xacro:arg name="use_nominal_extrinsics" default="false"/>
  <xacro:arg name="add_plug" default="false" />
  <xacro:arg name="use_mesh" default="true" />

  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
  
  <xacro:sensor_d435 parent="camera_base_link" use_nominal_extrinsics="$(arg use_nominal_extrinsics)" add_plug="$(arg add_plug)" use_mesh="$(arg use_mesh)">
    <origin xyz="0.0 -0.0125 -0.01015" rpy="0 ${pi/2} ${pi/2}" />
  </xacro:sensor_d435>

<!-- Jig Robot -->

<!-- Use same joint names as robot so I can reuse ros2 controls -->
  <joint name="left_joint_1" type="revolute">
      <origin xyz="0 0.008 -0.548" rpy="${-pi/2} 0 0"/>
      <parent link="rack"/>
      <child link="aruco_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-pi}" upper="${pi}" effort="5.0" velocity="10.0"/>
  </joint>

  <link name="aruco_link">
    <visual>
      <geometry>
        <!-- <mesh filename="package://bam_descriptions/meshes/aruco/ground_truth_board.stl"/> -->
        <mesh filename="package://bam_descriptions/meshes/aruco/aruco_link.stl"/>
      </geometry>
      <material name="Ghost"/>
    </visual>
  </link>


<!-- For Charuco Board -->
  <!-- <joint name="aruco_object_center" type="fixed">
      <origin xyz="-0.0675 -0.0015  0.028" rpy="1.052233 -1.570796 -2.62303"/>
      <parent link="aruco_link"/>
      <child link="aruco_white"/>
  </joint>

  <link name="aruco_white">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://bam_descriptions/meshes/aruco/aruco_board.stl"/>
      </geometry>
      <material name="White"/>
    </visual>
  </link> -->

  <xacro:include filename="$(find bam_descriptions)/urdf/aruco_calib.ros2_control.xacro"/>
  <xacro:aruco_calib_ros2_control transport_path="${transport_path}" use_mock_hardware="${mock_hardware}"/>


  <joint name="aruco_object_center" type="fixed">
      <origin xyz="0 0 ${0.031245+0.04}" rpy="1.382086 0 0"/>
      <parent link="aruco_link"/>
      <child link="aruco_white"/>
  </joint>

  <link name="aruco_white">
    <visual>
      <geometry>
        <mesh filename="package://bam_descriptions/meshes/aruco/aruco_white.stl"/>
      </geometry>
      <material name="White"/>
    </visual>
  </link>

  <joint name="aruco_black_joint" type="fixed">
      <parent link="aruco_white"/>
      <child link="aruco_black"/>
  </joint>

  <link name="aruco_black">
    <visual>
      <geometry>
        <mesh filename="package://bam_descriptions/meshes/aruco/aruco_black.stl"/>
      </geometry>
      <material name="Black"/>
    </visual>
  </link>

 <joint name="aruco_frame_joint" type="fixed">
      <parent link="aruco_white"/>
      <child link="aruco_frame"/>
  </joint>

  <link name="aruco_frame">
    <visual>
      <geometry>
        <mesh filename="package://bam_descriptions/meshes/aruco/cord_frame.stl"/>
      </geometry>
      <material name="Ghost"/>
    </visual>
  </link> 

  <!-- <xacro:property name="cube_width" value="0.026" /> -->


  <!-- <joint name="marker_1_joint" type="fixed">
    <origin xyz="0 0 ${cube_width/2}" rpy="0 0 0"/>
    <parent link="object_center"/>
    <child link="marker_1_center"/>
</joint>

  <link name="marker_1_center">
  </link> -->

</robot>

